# Generated by Django 5.2.8 on 2026-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('base_total', models.IntegerField()),
                ('height_m', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('classfication', models.CharField(max_length=100)),
                ('capture_rate', models.IntegerField()),
            ],
            options={
                'ordering': ['pokedex_number'],
            },
        ),
    ]
